export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const FETCH_LOCAL_WINDOWS = 'FETCH_LOCAL';
export const FETCHED_LOCAL_WINDOWS = 'FETCHED_LOCAL_WINDOWS';
export const FETCH_REMOTE_WINDOWS = 'FETCH_REMOTE_WINDOWS';
export const FETCHED_REMOTE_WINDOWS = 'FETCHED_REMOTE_WINDOWS';
export const SAVE_WINDOW = 'SAVE_WINDOW';
export const SAVED_WINDOW = 'SAVED_WINDOW';
export const UPDATE_WINDOW = 'UPDATE_WINDOW';
