export const FETCH_LOCAL_WINDOWS = 'FETCH_LOCAL';
export const FETCHED_LOCAL_WINDOWS = 'FETCHED_LOCAL_WINDOWS';
export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const UPDATED_WINDOW = 'UPDATED_WINDOW';
export const MONITOR_WINDOW = 'MONITOR_WINDOW';
export const MONITORING_WINDOW = 'MONITORING_WINDOW';
export const STOP_MONITORING_WINDOW = 'STOP_MONITORING_WINDOW';
